### ISSUE TITLE
Decompressing large file triggers OOM

### ISSUE THREAD

**Issue by AlexandruCihodaru** [intel/qatgo#1]
I am trying to decompress a file that when decompressed will have around 4GB. This makes the program crash with fatal error: runtime: out of memory.
```
runtime.systemstack_switch()
        /usr/lib/go-1.20/src/runtime/asm_amd64.s:463 fp=0xc0001e9410 sp=0xc0001e9408 pc=0x46da80
runtime.(*mheap).alloc(0x4000002000?, 0x2000001?, 0x60?)
        /usr/lib/go-1.20/src/runtime/mheap.go:955 +0x65 fp=0xc0001e9458 sp=0xc0001e9410 pc=0x4323e5
runtime.(*mcache).allocLarge(0x7fece37a2108?, 0x4000000200, 0x1)
        /usr/lib/go-1.20/src/runtime/mcache.go:234 +0x85 fp=0xc0001e94a0 sp=0xc0001e9458 pc=0x421de5
runtime.mallocgc(0x4000000200, 0x5e85a0, 0x1)
        /usr/lib/go-1.20/src/runtime/malloc.go:1053 +0x4f7 fp=0xc0001e9508 sp=0xc0001e94a0 pc=0x419537
runtime.makeslice(0x4000000200?, 0xc040600000?, 0x643d88?)
        /usr/lib/go-1.20/src/runtime/slice.go:103 +0x52 fp=0xc0001e9530 sp=0xc0001e9508 pc=0x456872
github.com/intel/qatgo/qatzip.(*Reader).Read(0xc020416000, {0xc020418028, 0x200, 0x200})
```

**Comment by markbrown314** [comment]
The current implementation of QATzip (which QATgo is based on) is [stateless](https://github.com/intel/QATzip/blob/3bcbb6c8136e9fe4f9f885bc0d8e86fdc5b8860f/src/qatzip_utils.c#L253), so you need to fully buffer the output file in memory. I will talk with the QAT team to see if there is a way to reduce memory consumption.

**Comment by markbrown314** [comment]
My initial assessment was incorrect. The bug here was due to how QZ_BUF_ERROR is handled. The error is triggered when QAT attempts to decompress content into a buffer that it is too small. This triggered a QATgo error handler to unnecessarily expand the output buffer and cause the OOM error. The only case when buffer expansion should happen is when the number of bytes outputted is zero. Go also has a slice limitation of 2GB which is limit we need to check for. Working on a fix for it.

**Comment by markbrown314** [comment]
@AlexandruCihodaru please try 1.1.0-rc1 to see if it resolves your issue.

**Comment by markbrown314** [comment]
I received some good initial feedback from @AlexandruCihodaru. We will leave this in release candidate until Wednesday and merge into main v.1.1.0. Please reopen if any issues are found with the bugfix.
